import { type Article, type Region } from "./types";

const mockArticlesByRegion: Record<Region, Article[]> = {
  japan: Array.from({ length: 10 }, (_, i) => ({
    id: `jp-${i + 1}`,
    title: [
      "日銀、金融政策の現状維持を決定",
      "東京都、新たな再開発計画を発表",
      "トヨタ、次世代EV戦略を公開",
      "大谷翔平、シーズン新記録を更新",
      "政府、デジタル庁の機能強化を閣議決定",
      "東京証券取引所、史上最高値を更新",
      "気象庁、梅雨入りを発表",
      "新幹線の新路線計画が承認",
      "ソニー、新型ゲーム機を発表",
      "日本の宇宙開発、新たなロケット打ち上げに成功",
    ][i],
    summary: [
      "日本銀行は金融政策決定会合で、現行の金融緩和政策を維持することを決定した。今後の経済見通しについても議論が行われた。",
      "東京都は臨海部を中心とした大規模再開発計画を正式に発表。2030年までに新たな都市機能の集積を目指す。",
      "トヨタ自動車は2030年までのEV戦略を発表。全固体電池の実用化を含む包括的な電動化計画を公開した。",
      "大谷翔平選手がメジャーリーグで新たなシーズン記録を樹立。投打の二刀流で歴史的な活躍を見せている。",
      "政府はデジタル庁の権限と機能を大幅に強化する方針を閣議決定。行政のデジタル化を加速させる。",
      "東京証券取引所の日経平均株価が史上最高値を更新。海外投資家の買いが相場を押し上げた。",
      "気象庁は関東甲信地方が梅雨入りしたとみられると発表。平年より3日早い梅雨入りとなった。",
      "国土交通省は新幹線の新たな路線計画を正式に承認。2035年の開業を目指す。",
      "ソニー・インタラクティブエンタテインメントが次世代ゲーム機を発表。AIを活用した新機能を搭載。",
      "JAXAが開発した新型ロケットの打ち上げに成功。日本の宇宙開発は新たなステージへ。",
    ][i],
    source: ["NHK", "朝日新聞", "日経新聞", "読売新聞", "毎日新聞", "Bloomberg", "共同通信", "時事通信", "TechCrunch JP", "NHK"][i],
    sourceUrl: "https://example.com/article/" + (i + 1),
    publishedAt: new Date(Date.now() - i * 3600000).toISOString(),
    region: "japan",
    isRead: i > 4,
    category: "general",
  })),
  global: Array.from({ length: 10 }, (_, i) => ({
    id: `gl-${i + 1}`,
    title: [
      "UN Climate Summit Reaches Historic Agreement",
      "Federal Reserve Holds Interest Rates Steady",
      "AI Breakthrough: New Model Surpasses Human Performance",
      "Global Supply Chain Disruptions Ease",
      "WHO Declares End of Health Emergency",
      "SpaceX Successfully Launches Mars Mission",
      "EU Passes Comprehensive Digital Regulation",
      "Oil Prices Surge Amid Middle East Tensions",
      "Global Tech Giants Report Record Earnings",
      "International Trade Agreement Signed by 30 Nations",
    ][i],
    summary: [
      "World leaders at the UN Climate Summit have agreed to a landmark deal to reduce carbon emissions by 60% by 2035, marking the most ambitious climate agreement to date.",
      "The Federal Reserve announced it will maintain current interest rates, citing stable inflation and moderate economic growth in its latest policy statement.",
      "Researchers announce a major AI breakthrough with a new model that consistently outperforms human experts across multiple scientific domains.",
      "Global supply chain bottlenecks that plagued businesses for years are showing significant signs of improvement, with shipping costs returning to pre-pandemic levels.",
      "The World Health Organization has officially declared the end of the global health emergency, noting sustained decline in cases worldwide.",
      "SpaceX has successfully launched its first crewed mission to Mars, marking a historic milestone in human space exploration.",
      "The European Union has passed sweeping new digital regulations that will affect how tech companies operate across the continent.",
      "Oil prices have surged to their highest level in months as geopolitical tensions in the Middle East raise concerns about supply disruptions.",
      "Major technology companies have reported record-breaking quarterly earnings, driven by strong demand for AI products and cloud services.",
      "Thirty nations have signed a new international trade agreement aimed at reducing tariffs and promoting sustainable commerce.",
    ][i],
    source: ["Reuters", "AP News", "BBC", "Bloomberg", "CNN", "The Guardian", "Financial Times", "Al Jazeera", "CNBC", "The Economist"][i],
    sourceUrl: "https://example.com/article/" + (i + 1),
    publishedAt: new Date(Date.now() - i * 3600000).toISOString(),
    region: "global",
    isRead: i > 5,
    category: "general",
  })),
  taiwan: Array.from({ length: 10 }, (_, i) => ({
    id: `tw-${i + 1}`,
    title: [
      "台積電宣布新一代製程技術突破",
      "台灣半導體產業鏈持續擴大",
      "行政院通過新數位發展政策",
      "台北市推動智慧城市計畫",
      "台灣觀光業復甦超出預期",
      "台股指數創下歷史新高",
      "台灣再生能源發展加速",
      "教育部推動雙語教育政策",
      "台灣國際醫療合作新進展",
      "台灣文化創意產業蓬勃發展",
    ][i],
    summary: [
      "台積電在技術論壇上宣布其最新製程技術取得重大突破，預計將在未來兩年內量產，進一步鞏固其全球領先地位。",
      "台灣半導體產業鏈持續擴大，吸引更多國際企業進駐，形成更完整的產業生態系統。",
      "行政院通過新的數位發展政策，將投入大量資源推動AI、5G及數位基礎建設。",
      "台北市政府啟動新一階段智慧城市計畫，運用IoT和大數據技術提升城市治理效率。",
      "台灣觀光業在國際旅客回流帶動下快速復甦，今年旅客人數已超出年度目標。",
      "台灣加權股價指數突破歷史新高，科技股表現亮眼，帶動整體市場信心。",
      "台灣加速推動再生能源發展，離岸風電和太陽能裝置容量持續增長。",
      "教育部宣布擴大雙語教育政策範圍，目標在2030年前實現全面雙語教學環境。",
      "台灣在國際醫療合作方面取得新進展，多項合作計畫獲得國際認可。",
      "台灣文化創意產業蓬勃發展，在國際市場上的影響力持續擴大。",
    ][i],
    source: ["中央社", "自由時報", "聯合報", "中國時報", "TVBS", "民視", "三立新聞", "公視", "經濟日報", "工商時報"][i],
    sourceUrl: "https://example.com/article/" + (i + 1),
    publishedAt: new Date(Date.now() - i * 3600000).toISOString(),
    region: "taiwan",
    isRead: i > 3,
    category: "general",
  })),
  us: Array.from({ length: 10 }, (_, i) => ({
    id: `us-${i + 1}`,
    title: [
      "Congress Passes Bipartisan Infrastructure Bill",
      "Silicon Valley Tech Layoffs Continue",
      "US Housing Market Shows Signs of Recovery",
      "NASA Announces New Lunar Mission Timeline",
      "Supreme Court Issues Landmark Privacy Ruling",
      "US Economy Adds 300,000 Jobs in Latest Report",
      "Major Cybersecurity Legislation Advances",
      "Electric Vehicle Adoption Hits Record High",
      "US Education Reform Bill Gains Support",
      "Healthcare Costs Continue to Rise Across States",
    ][i],
    summary: [
      "Congress has passed a bipartisan infrastructure bill allocating $1.2 trillion for roads, bridges, broadband, and clean energy projects across the nation.",
      "Major Silicon Valley companies continue to announce layoffs as the tech industry restructures amid shifting market conditions and AI adoption.",
      "The US housing market is showing signs of recovery with increased home sales and stabilizing prices after a prolonged downturn.",
      "NASA has announced an updated timeline for its Artemis lunar program, with crewed missions to the Moon's surface planned within the next two years.",
      "The Supreme Court has issued a landmark ruling on digital privacy rights, significantly expanding protections for personal data.",
      "The US economy added 300,000 jobs last month, exceeding expectations and signaling continued strength in the labor market.",
      "Major cybersecurity legislation is advancing through Congress with bipartisan support, aimed at protecting critical infrastructure.",
      "Electric vehicle sales in the US have reached a record high, now accounting for 15% of all new car purchases.",
      "A comprehensive education reform bill is gaining bipartisan support in Congress, focusing on STEM education and teacher compensation.",
      "Healthcare costs continue to rise across all US states, prompting calls for legislative action to address affordability.",
    ][i],
    source: ["CNN", "NYT", "Washington Post", "AP News", "NPR", "Bloomberg", "Fox News", "CNBC", "USA Today", "Politico"][i],
    sourceUrl: "https://example.com/article/" + (i + 1),
    publishedAt: new Date(Date.now() - i * 3600000).toISOString(),
    region: "us",
    isRead: i > 5,
    category: "general",
  })),
  eu: Array.from({ length: 10 }, (_, i) => ({
    id: `eu-${i + 1}`,
    title: [
      "EU Digital Markets Act Takes Full Effect",
      "ECB Adjusts Monetary Policy Strategy",
      "European Green Deal Milestones Achieved",
      "Brexit Trade Adjustments Continue",
      "France Announces Major Education Reform",
      "Germany Leads European AI Initiative",
      "EU Migration Policy Reform Advances",
      "European Space Agency Plans New Missions",
      "Italy's Cultural Heritage Digitization Project",
      "Nordic Countries Top Global Happiness Index",
    ][i],
    summary: [
      "The EU Digital Markets Act is now fully in effect, imposing new rules on major tech platforms to ensure fair competition in the European market.",
      "The European Central Bank has announced adjustments to its monetary policy strategy, reflecting changing economic conditions across the eurozone.",
      "The European Union has achieved several key milestones in its Green Deal initiative, including significant reductions in carbon emissions.",
      "Post-Brexit trade adjustments continue as businesses adapt to new regulations governing trade between the UK and EU member states.",
      "France has announced a major education reform plan focusing on digital literacy and preparing students for the future workforce.",
      "Germany is leading a new EU-wide artificial intelligence initiative, committing significant funding to research and development.",
      "EU migration policy reform is advancing with new proposals for a unified approach to asylum and border management.",
      "The European Space Agency has unveiled plans for several new space missions, including deep space exploration and Earth observation.",
      "Italy has launched an ambitious project to digitize its vast cultural heritage, making art and historical artifacts accessible worldwide.",
      "Nordic countries once again top the global happiness index, with Finland, Denmark, and Sweden leading the rankings.",
    ][i],
    source: ["Euronews", "DW", "France24", "BBC Europe", "The Guardian", "Politico EU", "El País", "Corriere", "NRC", "SVT"][i],
    sourceUrl: "https://example.com/article/" + (i + 1),
    publishedAt: new Date(Date.now() - i * 3600000).toISOString(),
    region: "eu",
    isRead: i > 4,
    category: "general",
  })),
  latam: Array.from({ length: 10 }, (_, i) => ({
    id: `la-${i + 1}`,
    title: [
      "Brasil Anuncia Plan de Energía Renovable",
      "México Fortalece Industria Manufacturera",
      "Argentina Implementa Reformas Económicas",
      "Chile Lidera en Energía Solar en la Región",
      "Colombia Avanza en Acuerdos de Paz",
      "Perú Impulsa Desarrollo Turístico Sostenible",
      "Cumbre Latinoamericana de Tecnología en São Paulo",
      "Uruguay Destaca en Educación Digital",
      "Costa Rica Alcanza Meta de Carbono Neutro",
      "Mercosur Firma Nuevo Acuerdo Comercial",
    ][i],
    summary: [
      "Brasil ha anunciado un ambicioso plan para expandir su capacidad de energía renovable, con inversiones significativas en energía eólica y solar.",
      "México continúa fortaleciendo su industria manufacturera, atrayendo inversiones extranjeras y diversificando su base productiva.",
      "Argentina ha implementado una serie de reformas económicas dirigidas a estabilizar la moneda y reducir la inflación.",
      "Chile se consolida como líder regional en energía solar, con nuevos proyectos que aumentarán significativamente su capacidad instalada.",
      "Colombia ha logrado avances significativos en sus procesos de paz, con nuevos acuerdos alcanzados con grupos armados.",
      "Perú está impulsando un plan de desarrollo turístico sostenible que busca proteger su patrimonio cultural y natural.",
      "São Paulo será sede de la cumbre tecnológica más grande de Latinoamérica, reuniendo a líderes de innovación de toda la región.",
      "Uruguay se destaca en la región por sus avances en educación digital, con un programa que conecta a todos los estudiantes.",
      "Costa Rica ha alcanzado su meta de carbono neutro, convirtiéndose en uno de los primeros países en lograrlo.",
      "Los países del Mercosur han firmado un nuevo acuerdo comercial que facilitará el intercambio de bienes y servicios en la región.",
    ][i],
    source: ["Folha", "El Universal", "Clarín", "La Tercera", "El Tiempo", "El Comercio", "Reuters LATAM", "BBC Mundo", "CNN Español", "Infobae"][i],
    sourceUrl: "https://example.com/article/" + (i + 1),
    publishedAt: new Date(Date.now() - i * 3600000).toISOString(),
    region: "latam",
    isRead: i > 5,
    category: "general",
  })),
};

export function getMockArticles(region: Region): Article[] {
  return mockArticlesByRegion[region] || [];
}

export const mockPaidSiteArticles: Article[] = Array.from({ length: 5 }, (_, i) => ({
  id: `paid-${i + 1}`,
  title: [
    "独占レポート：次世代AI技術の最前線",
    "Market Analysis: Q4 Global Outlook",
    "深度報導：亞洲經濟轉型",
    "Exclusive: Inside the Future of Quantum Computing",
    "特別企画：持続可能な都市開発の未来",
  ][i],
  summary: [
    "最新のAI技術動向を独自取材。大手テック企業の開発競争の実態と今後の展望を詳しく解説。",
    "Comprehensive analysis of global market trends for Q4, with insights into emerging opportunities and potential risks across major sectors.",
    "深入探討亞洲各國經濟轉型的進展，分析未來發展趨勢與挑戰。",
    "An exclusive look at the latest developments in quantum computing, featuring interviews with leading researchers and industry experts.",
    "世界各地の持続可能な都市開発プロジェクトを特集。最新のグリーンテクノロジーと都市計画の融合を解説。",
  ][i],
  source: ["日経新聞", "Financial Times", "天下雜誌", "The Economist", "朝日新聞"][i],
  sourceUrl: "https://example.com/paid/" + (i + 1),
  publishedAt: new Date(Date.now() - i * 7200000).toISOString(),
  region: "global",
  isRead: i > 2,
  category: "paid",
}));

export const mockCompanyArticles: Article[] = Array.from({ length: 5 }, (_, i) => ({
  id: `company-${i + 1}`,
  title: [
    "Apple、新型チップ「M5」を発表",
    "Tesla Reports Record Delivery Numbers",
    "台積電第三季營收創新高",
    "Microsoft Expands AI Partnership",
    "ソニー、メタバース事業に参入",
  ][i],
  summary: [
    "Appleは次世代プロセッサ「M5」を発表。前世代比で40%の性能向上を実現し、AI処理能力が大幅に強化された。",
    "Tesla has reported record vehicle deliveries for the quarter, exceeding analyst expectations with strong demand across all models.",
    "台積電公布第三季財報，營收創下歷史新高，先進製程需求持續強勁。",
    "Microsoft has announced an expanded partnership to integrate AI capabilities across its enterprise product lineup.",
    "ソニーグループがメタバース事業への本格参入を発表。エンタテインメント分野での新たな体験を提供する。",
  ][i],
  source: ["Apple Newsroom", "Tesla IR", "TSMC", "Microsoft Blog", "Sony Group"][i],
  sourceUrl: "https://example.com/company/" + (i + 1),
  publishedAt: new Date(Date.now() - i * 5400000).toISOString(),
  region: "global",
  isRead: i > 1,
  category: "companies",
}));
