import { type Article, type BuiltInRegion, type Region } from "./types";

const mockArticlesByRegion: Record<BuiltInRegion, Article[]> = {
  japan: Array.from({ length: 10 }, (_, i) => ({
    id: `jp-${i + 1}`,
    title: [
      "日銀、金融政策の現状維持を決定",
      "東京都、新たな再開発計画を発表",
      "トヨタ、次世代EV戦略を公開",
      "大谷翔平、シーズン新記録を更新",
      "政府、デジタル庁の機能強化を閣議決定",
      "東京証券取引所、史上最高値を更新",
      "気象庁、梅雨入りを発表",
      "新幹線の新路線計画が承認",
      "ソニー、新型ゲーム機を発表",
      "日本の宇宙開発、新たなロケット打ち上げに成功",
    ][i],
    summary: [
      "日本銀行は金融政策決定会合で、現行の金融緩和政策を維持することを全会一致で決定した。植田総裁は会見で、消費者物価指数の上昇率が目標の2%に近づきつつあるものの、持続的な賃金上昇の確認が必要との見解を示した。市場では次回会合での利上げ観測が高まっている。",
      "東京都は臨海部を中心とした総額2兆円規模の大規模再開発計画を正式に発表した。有明・豊洲エリアに国際ビジネス拠点や最先端の医療研究施設を新設し、2030年までにアジアの金融ハブとしての地位確立を目指す。住民向けの緑地整備や交通インフラの拡充も計画に含まれる。",
      "トヨタ自動車は2030年までの包括的EV戦略を発表した。全固体電池の2027年量産開始を核に、航続距離1,000kmを超える次世代EVの投入を計画。さらに、充電インフラへの5,000億円投資や、既存工場のEV生産ラインへの転換も明らかにした。",
      "大谷翔平選手がメジャーリーグで前人未到のシーズン60本塁打・25勝を達成し、歴史的な二刀流シーズンを更新した。投手としては防御率2.10、打者としては打率.310と両面で圧倒的な成績を残しており、満場一致でのMVP受賞が確実視されている。",
      "政府はデジタル庁の権限と機能を大幅に強化する方針を閣議決定した。各省庁のシステム統合の司令塔としての役割を明確化し、マイナンバーカードの利用範囲拡大、行政手続きの完全オンライン化、自治体システムの標準化を2026年度中に完了させる目標を掲げた。",
      "東京証券取引所の日経平均株価が4万5千円を突破し史上最高値を更新した。半導体関連銘柄の急騰と海外投資家の大規模買い越しが相場を押し上げた。アナリストは企業業績の好調と円安効果が背景にあると分析しており、年内5万円到達の予測も出始めている。",
      "気象庁は関東甲信地方が梅雨入りしたとみられると発表した。平年より3日早く、昨年より5日早い梅雨入り。今年は太平洋高気圧の張り出しが強く、西日本から東日本にかけて降水量が平年を上回る見込み。土砂災害や河川の増水への警戒が呼びかけられている。",
      "国土交通省は北陸新幹線の敦賀〜新大阪間の延伸計画を正式に承認した。総工費約3.7兆円、2035年の開業を目指す。京都市内は地下ルートを採用し、環境への影響を最小限に抑える設計となる。開業により東京〜新大阪間が約3時間で結ばれる見通し。",
      "ソニー・インタラクティブエンタテインメントが次世代ゲーム機「PlayStation 6」を発表した。カスタムAIプロセッサによるリアルタイム環境生成や、触覚フィードバックの大幅進化が特徴。クラウドゲーミングとのハイブリッド設計で、8K解像度でのゲームプレイも可能になる。",
      "JAXAが開発した新型ロケット「H3」改良型の打ち上げに成功し、月探査用中継衛星を所定の軌道に投入した。打ち上げコストを従来の半分に削減する技術が実証され、商業衛星打ち上げ市場での国際競争力が大幅に向上。今後は火星探査機の打ち上げも計画されている。",
    ][i],
    source: ["NHK", "朝日新聞", "日経新聞", "読売新聞", "毎日新聞", "Bloomberg", "共同通信", "時事通信", "TechCrunch JP", "NHK"][i],
    sourceUrl: "https://example.com/article/" + (i + 1),
    publishedAt: new Date(Date.now() - i * 3600000).toISOString(),
    region: "japan",
    isRead: i > 4,
    category: "general",
  })),
  global: Array.from({ length: 10 }, (_, i) => ({
    id: `gl-${i + 1}`,
    title: [
      "UN Climate Summit Reaches Historic Agreement",
      "Federal Reserve Holds Interest Rates Steady",
      "AI Breakthrough: New Model Surpasses Human Performance",
      "Global Supply Chain Disruptions Ease",
      "WHO Declares End of Health Emergency",
      "SpaceX Successfully Launches Mars Mission",
      "EU Passes Comprehensive Digital Regulation",
      "Oil Prices Surge Amid Middle East Tensions",
      "Global Tech Giants Report Record Earnings",
      "International Trade Agreement Signed by 30 Nations",
    ][i],
    summary: [
      "World leaders at the UN Climate Summit have agreed to a landmark deal to reduce carbon emissions by 60% by 2035, marking the most ambitious climate agreement to date. The agreement includes a $500 billion annual fund to help developing nations transition to clean energy, binding emission reduction targets for all signatory nations, and a new carbon trading mechanism. Critics argue the targets are still insufficient to limit warming to 1.5°C.",
      "The Federal Reserve announced it will maintain current interest rates at 5.25-5.50%, citing stable inflation at 2.3% and moderate economic growth of 2.1% in its latest policy statement. Chair Powell indicated that rate cuts could begin in the second half of the year if inflation continues its downward trajectory. Markets reacted positively, with the S&P 500 rising 1.2% following the announcement.",
      "Researchers at DeepMind announce a major AI breakthrough with a new model that consistently outperforms human experts across multiple scientific domains including drug discovery, materials science, and climate modeling. The model, trained on the largest scientific dataset ever assembled, can generate novel hypotheses and design experiments autonomously. The breakthrough is expected to accelerate scientific research by orders of magnitude.",
      "Global supply chain bottlenecks that plagued businesses for years are showing significant signs of improvement, with shipping costs returning to pre-pandemic levels. Container rates from Asia to North America have dropped 75% from their peak, factory lead times have normalized across major manufacturing hubs, and inventory levels at retailers are stabilizing. Economists warn that geopolitical risks could reverse these gains.",
      "The World Health Organization has officially declared the end of the global health emergency, noting a sustained 90% decline in cases worldwide over the past six months. WHO Director-General praised international cooperation but emphasized the need for continued investment in pandemic preparedness infrastructure, genomic surveillance systems, and equitable vaccine distribution to prevent future outbreaks.",
      "SpaceX has successfully launched its first crewed mission to Mars with a team of six astronauts, marking a historic milestone in human space exploration. The Starship vehicle entered its Mars transit orbit flawlessly after a nine-month journey that will make it the first crewed interplanetary mission. The crew includes scientists from five countries who will establish the first permanent research base on the Martian surface.",
      "The European Union has passed sweeping new digital regulations that will affect how tech companies operate across the continent. The Digital Markets Act imposes strict rules on platform gatekeepers including Apple, Google, Meta, and Amazon, requiring interoperability of messaging services, prohibiting self-preferencing in search results, and mandating data portability. Non-compliance penalties can reach up to 10% of global annual revenue.",
      "Oil prices have surged to $95 per barrel, their highest level in 18 months, as geopolitical tensions in the Middle East raise concerns about supply disruptions. Shipping through the Strait of Hormuz has been impacted by regional conflicts, and OPEC+ has maintained production cuts despite rising demand. Analysts warn that sustained high oil prices could reignite inflation in major economies and slow the global economic recovery.",
      "Major technology companies have reported record-breaking quarterly earnings, driven by strong demand for AI products and cloud services. Combined revenue from the top five tech firms exceeded $400 billion, with AI-related revenue growing 150% year-over-year. Cloud infrastructure spending surged as enterprises accelerated their AI adoption, while hardware sales benefited from the growing demand for AI-capable devices and data center equipment.",
      "Thirty nations have signed a new international trade agreement aimed at reducing tariffs by an average of 40% and promoting sustainable commerce. The agreement establishes common environmental standards for traded goods, creates a digital trade framework to facilitate cross-border e-commerce, and includes provisions for protecting intellectual property in the AI era. The deal is expected to boost global trade by $2 trillion annually.",
    ][i],
    source: ["Reuters", "AP News", "BBC", "Bloomberg", "CNN", "The Guardian", "Financial Times", "Al Jazeera", "CNBC", "The Economist"][i],
    sourceUrl: "https://example.com/article/" + (i + 1),
    publishedAt: new Date(Date.now() - i * 3600000).toISOString(),
    region: "global",
    isRead: i > 5,
    category: "general",
  })),
  taiwan: Array.from({ length: 10 }, (_, i) => ({
    id: `tw-${i + 1}`,
    title: [
      "台積電宣布新一代製程技術突破",
      "台灣半導體產業鏈持續擴大",
      "行政院通過新數位發展政策",
      "台北市推動智慧城市計畫",
      "台灣觀光業復甦超出預期",
      "台股指數創下歷史新高",
      "台灣再生能源發展加速",
      "教育部推動雙語教育政策",
      "台灣國際醫療合作新進展",
      "台灣文化創意產業蓬勃發展",
    ][i],
    summary: [
      "台積電在年度技術論壇上宣布其1.4奈米製程技術取得重大突破，採用全新的環繞式閘極電晶體架構，效能提升30%、功耗降低25%。預計將在2027年量產，已獲得蘋果、輝達等主要客戶的訂單承諾，進一步鞏固其在全球晶圓代工市場的領先地位。",
      "台灣半導體產業鏈持續擴大，今年已吸引超過50家國際企業在台設立研發中心或生產基地。從IC設計、製造到封裝測試，形成了亞洲最完整的半導體生態系統。政府同步推出稅務優惠和人才培育計畫，預計將創造超過3萬個高薪就業機會。",
      "行政院通過總額達3,000億元的新數位發展政策，將在未來五年大力推動AI產業化應用、5G專網建設及數位基礎設施升級。重點項目包括建立國家級AI運算中心、推動政府數位轉型，以及培育10萬名數位專業人才。",
      "台北市政府啟動新一階段智慧城市計畫「Smart Taipei 3.0」，運用IoT感測器、大數據分析和AI技術全面提升城市治理效率。計畫涵蓋智慧交通號誌系統、即時空氣品質監測、智慧路燈節能管理等項目，目標在三年內覆蓋全市12個行政區。",
      "台灣觀光業在國際旅客回流帶動下快速復甦，今年前三季旅客人數已達980萬人次，超出年度目標的95%。日本、韓國及東南亞旅客成長最為顯著，政府推出的「Taiwan the Lucky Land」行銷活動和簽證便利化措施成效明顯，旅遊相關產業營收較去年同期成長45%。",
      "台灣加權股價指數突破24,000點歷史新高，今年以來累計漲幅達28%。台積電等科技權值股表現亮眼，帶動整體市場信心。外資今年累計買超超過5,000億元，顯示國際投資人對台灣科技產業前景的高度信心。分析師預期年底前指數有望挑戰25,000點。",
      "台灣加速推動再生能源發展，離岸風電裝置容量已達8GW，太陽能則突破15GW，合計佔總發電量的20%。政府宣布第三階段離岸風電區塊開發計畫，預計新增15GW容量。同時，首座浮動式離岸風場也已完成環評，將成為亞太地區的重要示範案場。",
      "教育部宣布擴大雙語教育政策範圍，投入500億元預算推動全國中小學雙語教學。計畫包括引進3,000名外籍英語教師、建立線上雙語學習平台，以及將英語融入數學、科學等學科教學。目標在2030年前實現全面雙語教學環境，提升國際競爭力。",
      "台灣在國際醫療合作方面取得新進展，與日本、新加坡及歐盟簽署多項醫療技術交流協議。台灣的精準醫療和遠距醫療技術獲得國際認可，多家醫學中心與國際頂尖機構建立聯合研究計畫，聚焦於癌症免疫療法和罕見疾病治療。",
      "台灣文化創意產業蓬勃發展，今年文創產業總產值突破1兆元，較去年成長18%。台灣影視作品在國際串流平台表現亮眼，遊戲產業出口額創新高，設計品牌在米蘭設計週獲得多項大獎。政府宣布將文創產業列為六大核心戰略產業之一。",
    ][i],
    source: ["中央社", "自由時報", "聯合報", "中國時報", "TVBS", "民視", "三立新聞", "公視", "經濟日報", "工商時報"][i],
    sourceUrl: "https://example.com/article/" + (i + 1),
    publishedAt: new Date(Date.now() - i * 3600000).toISOString(),
    region: "taiwan",
    isRead: i > 3,
    category: "general",
  })),
  us: Array.from({ length: 10 }, (_, i) => ({
    id: `us-${i + 1}`,
    title: [
      "Congress Passes Bipartisan Infrastructure Bill",
      "Silicon Valley Tech Layoffs Continue",
      "US Housing Market Shows Signs of Recovery",
      "NASA Announces New Lunar Mission Timeline",
      "Supreme Court Issues Landmark Privacy Ruling",
      "US Economy Adds 300,000 Jobs in Latest Report",
      "Major Cybersecurity Legislation Advances",
      "Electric Vehicle Adoption Hits Record High",
      "US Education Reform Bill Gains Support",
      "Healthcare Costs Continue to Rise Across States",
    ][i],
    summary: [
      "Congress has passed a bipartisan infrastructure bill allocating $1.2 trillion for roads, bridges, broadband, and clean energy projects across the nation. The legislation includes $110 billion for roads and bridges, $65 billion for broadband expansion to underserved rural areas, $75 billion for clean energy grid upgrades, and $39 billion for public transit modernization. Construction is expected to create 1.5 million jobs over the next decade.",
      "Major Silicon Valley companies continue to announce layoffs as the tech industry restructures amid shifting market conditions and AI adoption. Over 150,000 positions have been eliminated this year across Google, Meta, Microsoft, and Amazon, with mid-level management and non-AI engineering roles most affected. Companies are simultaneously hiring for AI-focused positions, signaling a fundamental shift in the skills demanded by the technology sector.",
      "The US housing market is showing signs of recovery with increased home sales and stabilizing prices after a prolonged downturn. Existing home sales rose 8.2% last month, the largest monthly increase in two years, while mortgage rates dipped below 6% for the first time since 2023. However, housing affordability remains a challenge as median home prices are still 25% above pre-pandemic levels in major metropolitan areas.",
      "NASA has announced an updated timeline for its Artemis lunar program, with Artemis III crewed landing on the Moon's surface planned for late 2027. The mission will deploy the first woman and first person of color on the lunar surface, establish a permanent research outpost at the South Pole, and test technologies critical for future Mars missions. The agency also unveiled the next-generation spacesuit designs developed in partnership with Axiom Space.",
      "The Supreme Court has issued a landmark ruling on digital privacy rights, significantly expanding protections for personal data in a 7-2 decision. The ruling establishes that law enforcement agencies must obtain warrants before accessing individuals' digital records from third-party companies, including search histories, location data, and financial transactions. The decision overturns decades of precedent and is expected to reshape how tech companies handle user data.",
      "The US economy added 300,000 jobs last month, far exceeding the 180,000 forecast by economists, signaling continued strength in the labor market. Healthcare, technology, and construction sectors led the gains, while the unemployment rate fell to 3.5%. Average hourly earnings rose 4.1% year-over-year, outpacing inflation for the sixth consecutive month. The robust report has led economists to revise GDP growth forecasts upward to 3.2%.",
      "Major cybersecurity legislation is advancing through Congress with bipartisan support, aimed at protecting critical infrastructure from increasingly sophisticated state-sponsored attacks. The bill mandates real-time threat sharing between government and private sector, establishes minimum security standards for utilities and financial institutions, creates a $10 billion fund for cybersecurity workforce development, and imposes penalties for companies that fail to report breaches within 72 hours.",
      "Electric vehicle sales in the US have reached a record high, now accounting for 15% of all new car purchases with 1.2 million units sold last quarter. Tesla remains the market leader but its share has declined to 45% as legacy automakers ramp up production. The expansion of the national charging network to over 100,000 public stations and federal tax credits of up to $7,500 have been key drivers of adoption.",
      "A comprehensive education reform bill is gaining bipartisan support in Congress, focusing on STEM education and teacher compensation. The $200 billion proposal would increase minimum teacher salaries to $60,000 nationally, fund coding and AI literacy programs starting in elementary school, expand free community college access, and create 10,000 new apprenticeship programs in partnership with technology companies.",
      "Healthcare costs continue to rise across all US states, with average annual premiums for employer-sponsored family coverage reaching $25,000. The 7.5% year-over-year increase has prompted calls for legislative action, including proposals for drug price negotiation expansion, hospital price transparency enforcement, and a public option insurance plan. Rural areas are particularly affected, with 30% of rural hospitals at risk of closure due to financial pressures.",
    ][i],
    source: ["CNN", "NYT", "Washington Post", "AP News", "NPR", "Bloomberg", "Fox News", "CNBC", "USA Today", "Politico"][i],
    sourceUrl: "https://example.com/article/" + (i + 1),
    publishedAt: new Date(Date.now() - i * 3600000).toISOString(),
    region: "us",
    isRead: i > 5,
    category: "general",
  })),
  eu: Array.from({ length: 10 }, (_, i) => ({
    id: `eu-${i + 1}`,
    title: [
      "EU Digital Markets Act Takes Full Effect",
      "ECB Adjusts Monetary Policy Strategy",
      "European Green Deal Milestones Achieved",
      "Brexit Trade Adjustments Continue",
      "France Announces Major Education Reform",
      "Germany Leads European AI Initiative",
      "EU Migration Policy Reform Advances",
      "European Space Agency Plans New Missions",
      "Italy's Cultural Heritage Digitization Project",
      "Nordic Countries Top Global Happiness Index",
    ][i],
    summary: [
      "The EU Digital Markets Act is now fully in effect, imposing strict new rules on six designated gatekeeper platforms — Apple, Google, Meta, Amazon, Microsoft, and ByteDance. Companies must allow third-party app stores, enable cross-platform messaging interoperability, and stop self-preferencing their own services in search results. First enforcement actions have already been initiated against two companies, with potential fines of up to 10% of global revenue.",
      "The European Central Bank has announced a pivotal adjustment to its monetary policy strategy, cutting the benchmark interest rate by 25 basis points to 3.75% for the first time in two years. ECB President cited moderating inflation across the eurozone, now at 2.4%, and weakening economic growth in Germany and France as key factors. The decision signals a shift toward supporting economic recovery while maintaining price stability.",
      "The European Union has achieved several key milestones in its Green Deal initiative, with carbon emissions falling 32% below 1990 levels. Renewable energy now accounts for 45% of the EU's electricity generation, exceeding the 2025 target two years early. The EU also launched a €100 billion green bond program to fund the next phase of the transition, including hydrogen infrastructure and building renovation across all 27 member states.",
      "Post-Brexit trade adjustments continue as businesses adapt to new regulations governing trade between the UK and EU member states. New customs checks have increased border processing times by 40%, costing businesses an estimated £7 billion annually. Both sides are negotiating a revised veterinary agreement to ease food trade friction, while the UK's financial services sector seeks improved access to European markets through a new memorandum of understanding.",
      "France has announced a €50 billion education reform plan focusing on digital literacy and preparing students for the AI-driven future workforce. The plan includes mandatory coding education from age 8, partnerships with tech companies to equip all schools with AI learning tools, a 15% increase in teacher salaries over three years, and the creation of 200 new vocational training centers specializing in green technology and digital skills.",
      "Germany is leading a new EU-wide artificial intelligence initiative with a combined investment of €20 billion over five years. The program establishes six pan-European AI research centers, creates regulatory sandboxes for AI innovation in healthcare and autonomous vehicles, and funds 50,000 AI scholarships for European students. Germany alone is contributing €8 billion, positioning itself as the continent's leading hub for responsible AI development.",
      "EU migration policy reform is advancing with the adoption of the New Pact on Migration and Asylum, establishing a unified approach to border management and refugee processing. The framework introduces mandatory solidarity contributions from all member states, faster asylum processing within 12 weeks, and strengthened partnerships with North African nations. The agreement, reached after eight years of negotiations, represents the most significant overhaul of EU migration policy in decades.",
      "The European Space Agency has unveiled an ambitious €18 billion plan for the next five years, including a Mars sample return mission, the construction of a lunar gateway module, and the deployment of 24 next-generation Earth observation satellites. The program also includes Europe's first independent crewed space vehicle and a dedicated space debris removal mission. ESA aims to strengthen Europe's strategic autonomy in space access.",
      "Italy has launched a €2 billion project to digitize its vast cultural heritage, making 50 million artworks, manuscripts, and historical artifacts accessible worldwide through an immersive digital platform. Using 3D scanning, AI restoration, and virtual reality technology, the initiative will create digital twins of major museums including the Uffizi, Vatican Museums, and Pompeii archaeological site. The platform is expected to attract 100 million virtual visitors annually.",
      "Nordic countries once again top the global happiness index for the seventh consecutive year, with Finland, Denmark, and Sweden leading the rankings. The report attributes their success to strong social safety nets, high trust in institutions, work-life balance policies including 480 days of parental leave, universal healthcare, and free higher education. The Nordic model is increasingly studied by other nations seeking to improve citizen well-being.",
    ][i],
    source: ["Euronews", "DW", "France24", "BBC Europe", "The Guardian", "Politico EU", "El País", "Corriere", "NRC", "SVT"][i],
    sourceUrl: "https://example.com/article/" + (i + 1),
    publishedAt: new Date(Date.now() - i * 3600000).toISOString(),
    region: "eu",
    isRead: i > 4,
    category: "general",
  })),
  latam: Array.from({ length: 10 }, (_, i) => ({
    id: `la-${i + 1}`,
    title: [
      "Brasil Anuncia Plan de Energía Renovable",
      "México Fortalece Industria Manufacturera",
      "Argentina Implementa Reformas Económicas",
      "Chile Lidera en Energía Solar en la Región",
      "Colombia Avanza en Acuerdos de Paz",
      "Perú Impulsa Desarrollo Turístico Sostenible",
      "Cumbre Latinoamericana de Tecnología en São Paulo",
      "Uruguay Destaca en Educación Digital",
      "Costa Rica Alcanza Meta de Carbono Neutro",
      "Mercosur Firma Nuevo Acuerdo Comercial",
    ][i],
    summary: [
      "Brasil ha anunciado un ambicioso plan de $80 mil millones para expandir su capacidad de energía renovable en un 150% para 2030. El programa incluye la construcción de 50 nuevos parques eólicos en el nordeste, el mayor complejo solar del hemisferio sur en Minas Gerais, y la modernización de la red hidroeléctrica amazónica. Se espera crear 500,000 empleos verdes y posicionar a Brasil como el mayor exportador de energía limpia de América Latina.",
      "México continúa fortaleciendo su industria manufacturera con la atracción de $35 mil millones en inversión extranjera directa este año, un récord histórico. El fenómeno de nearshoring ha impulsado la instalación de más de 200 nuevas plantas industriales, principalmente de empresas asiáticas y europeas que buscan diversificar sus cadenas de suministro. Los estados de Nuevo León, Jalisco y Querétaro lideran la captación de inversiones en los sectores automotriz y electrónico.",
      "Argentina ha implementado una serie de reformas económicas dirigidas a estabilizar el peso y reducir la inflación, que ha bajado del 140% al 45% anual en los últimos seis meses. Las medidas incluyen un estricto control del gasto público, liberalización parcial del mercado cambiario, y un programa de incentivos para la exportación agroindustrial. El FMI ha elogiado los avances pero advierte que la sostenibilidad depende de reformas estructurales más profundas.",
      "Chile se consolida como líder regional en energía solar, con la inauguración del parque solar más grande de Sudamérica en el desierto de Atacama, con una capacidad de 1.5 GW. El país ya genera el 40% de su electricidad con fuentes renovables y se ha fijado la meta de alcanzar el 80% para 2030. Además, Chile está desarrollando la mayor planta de hidrógeno verde del mundo, con inversiones de $8 mil millones de consorcios europeos.",
      "Colombia ha logrado avances significativos en sus procesos de paz, firmando un acuerdo de cese al fuego definitivo con el último grupo armado activo. El acuerdo incluye programas de reintegración social para 5,000 excombatientes, inversiones de $3 mil millones en infraestructura para zonas afectadas por el conflicto, y la creación de tribunales de justicia transicional. La comunidad internacional ha comprometido $2 mil millones adicionales en apoyo.",
      "Perú está impulsando un plan de desarrollo turístico sostenible de $5 mil millones que busca proteger su patrimonio cultural y natural mientras duplica el número de visitantes internacionales. El programa incluye mejoras en la infraestructura de acceso a Machu Picchu con un sistema de teleférico ecológico, restauración de sitios arqueológicos en la región de Cusco, y desarrollo de ecoturismo en la Amazonía peruana con participación activa de comunidades indígenas.",
      "São Paulo será sede de la cumbre tecnológica más grande de Latinoamérica, LATAM Tech Summit, que reunirá a más de 50,000 participantes y 500 empresas de innovación de toda la región. El evento contará con la participación de CEOs de las principales startups unicornio latinoamericanas y presentará $10 mil millones en oportunidades de inversión. Los temas principales incluyen inteligencia artificial, fintech, healthtech y la transición digital de las economías regionales.",
      "Uruguay se destaca en la región por sus avances en educación digital, con su programa Plan Ceibal que ha conectado al 100% de los estudiantes de primaria y secundaria con dispositivos y acceso a internet. El país ha expandido el programa para incluir cursos de programación, robótica e inteligencia artificial desde los 6 años. Los resultados en pruebas internacionales PISA muestran mejoras significativas, posicionando a Uruguay como referente educativo en América Latina.",
      "Costa Rica ha alcanzado su meta de carbono neutro, convirtiéndose en el primer país de América Latina y uno de los primeros del mundo en lograrlo. El logro se basa en una matriz eléctrica 99% renovable, un ambicioso programa de reforestación que ha duplicado la cobertura forestal del país, y la electrificación del 30% del transporte público. El modelo costarricense está siendo estudiado por más de 20 países como referencia para sus propias estrategias climáticas.",
      "Los países del Mercosur han firmado un histórico acuerdo comercial con la Unión Europea tras 25 años de negociaciones, creando la mayor zona de libre comercio del mundo con un mercado combinado de 780 millones de personas. El acuerdo eliminará aranceles sobre el 95% de los productos intercambiados en un período de 10 años, incluye cláusulas de protección ambiental y laboral, y se espera que aumente el comercio bilateral en $100 mil millones anuales.",
    ][i],
    source: ["Folha", "El Universal", "Clarín", "La Tercera", "El Tiempo", "El Comercio", "Reuters LATAM", "BBC Mundo", "CNN Español", "Infobae"][i],
    sourceUrl: "https://example.com/article/" + (i + 1),
    publishedAt: new Date(Date.now() - i * 3600000).toISOString(),
    region: "latam",
    isRead: i > 5,
    category: "general",
  })),
};

export function getMockArticles(region: Region): Article[] {
  const builtIn = mockArticlesByRegion[region as BuiltInRegion];
  if (builtIn) return builtIn;

  // For custom regions, return global articles relabeled with the custom region
  return (mockArticlesByRegion.global || []).map((a, i) => ({
    ...a,
    id: `${region}-${i + 1}`,
    region,
  }));
}

export const mockPaidSiteArticles: Article[] = Array.from({ length: 5 }, (_, i) => ({
  id: `paid-${i + 1}`,
  title: [
    "独占レポート：次世代AI技術の最前線",
    "Market Analysis: Q4 Global Outlook",
    "深度報導：亞洲經濟轉型",
    "Exclusive: Inside the Future of Quantum Computing",
    "特別企画：持続可能な都市開発の未来",
  ][i],
  summary: [
    "最新のAI技術動向を独自取材。OpenAI、Google DeepMind、Anthropicの三つ巴の開発競争の実態を関係者への取材で明らかにした。次世代モデルの推論能力は人間の専門家を大幅に上回り、科学研究や創薬分野での応用が急速に進む。一方で、AI安全性をめぐる各社の方針の違いや、規制当局との攻防も詳しく解説。",
    "Comprehensive analysis of global market trends for Q4, with deep insights into emerging opportunities and potential risks across major sectors. The report covers the impact of central bank policy divergence on currency markets, the continued AI-driven rally in tech stocks, growing concerns about commercial real estate defaults, and shifting dynamics in commodity markets as the energy transition accelerates.",
    "深入探討亞洲各國經濟轉型的進展，從中國的內需擴大政策、印度的製造業崛起、到東南亞的數位經濟爆發，全面分析未來十年亞洲經濟版圖的重塑。專訪多位經濟學家及企業領袖，剖析地緣政治風險、供應鏈重組、以及人口結構變化對區域經濟的深遠影響。",
    "An exclusive look at the latest developments in quantum computing, featuring interviews with IBM, Google, and PsiQuantum researchers. The report reveals that error-corrected quantum computers capable of solving commercially relevant problems may arrive within three years — far sooner than previously expected. Key applications in drug discovery, financial modeling, and cryptography are explored in detail.",
    "世界各地の持続可能な都市開発プロジェクトを特集。シンガポールの垂直農業都市構想、コペンハーゲンのカーボンニュートラル地区、東京・晴海のスマートシティ計画など、最先端のグリーンテクノロジーと都市計画の融合事例を現地取材。建築・エネルギー・交通の各分野における革新的技術の実用化状況を解説。",
  ][i],
  source: ["日経新聞", "Financial Times", "天下雜誌", "The Economist", "朝日新聞"][i],
  sourceUrl: "https://example.com/paid/" + (i + 1),
  publishedAt: new Date(Date.now() - i * 7200000).toISOString(),
  region: "global",
  isRead: i > 2,
  category: "paid",
}));

export const mockCompanyArticles: Article[] = Array.from({ length: 5 }, (_, i) => ({
  id: `company-${i + 1}`,
  title: [
    "Apple、新型チップ「M5」を発表",
    "Tesla Reports Record Delivery Numbers",
    "台積電第三季營收創新高",
    "Microsoft Expands AI Partnership",
    "ソニー、メタバース事業に参入",
  ][i],
  summary: [
    "Appleは次世代プロセッサ「M5」を発表した。3nmプロセスで製造され、前世代比で40%の性能向上と30%の電力効率改善を実現。特にニューラルエンジンが大幅に強化され、デバイス上でのAI処理がリアルタイムで可能に。MacBook ProとMac Studioへの搭載が来月から開始される。",
    "Tesla has reported record vehicle deliveries of 620,000 units for the quarter, exceeding analyst expectations by 15% with strong demand across all models. The affordable Model 2 accounted for 40% of deliveries, while the Cybertruck reached full production capacity. Revenue grew 25% year-over-year to $28 billion, and the company raised its annual delivery target to 2.2 million vehicles.",
    "台積電公布第三季財報，營收達7,500億元創下歷史新高，較去年同期成長35%。先進製程（5nm及以下）佔營收比重達68%，AI相關晶片需求持續強勁。公司上調全年營收預測並宣布在日本熊本和美國亞利桑那的新工廠將提前投產。",
    "Microsoft has announced a $30 billion expanded partnership with OpenAI to integrate advanced AI capabilities across its entire enterprise product lineup. The initiative includes embedding next-generation AI assistants in Office 365, Azure cloud services, and Dynamics 365. Early enterprise adopters report 40% productivity gains, and Microsoft expects AI-related revenue to reach $50 billion annually within two years.",
    "ソニーグループがメタバース事業への本格参入を発表した。PlayStation VR3のモーションキャプチャー技術と、ソニーミュージック・ソニーピクチャーズのコンテンツ資産を融合させ、音楽ライブや映画体験の仮想空間を構築する。初期投資額は3,000億円で、2027年までに1億人のユーザー獲得を目指す。",
  ][i],
  source: ["Apple Newsroom", "Tesla IR", "TSMC", "Microsoft Blog", "Sony Group"][i],
  sourceUrl: "https://example.com/company/" + (i + 1),
  publishedAt: new Date(Date.now() - i * 5400000).toISOString(),
  region: "global",
  isRead: i > 1,
  category: "companies",
}));
